Repository opencomputeproject/SAI, pull requests merged in 2024-11, with the labels that each got.

#2013 Next hop group with members.
  doc/ECMP/NextHopGroup_with_members.md
  inc/sainexthopgroup.h
Labels: reviewed

#2045 Prefix Compression feature addition to SAI
  doc/SAI-Proposal-Prefix-Compression.md
  inc/sai.h
  inc/saiacl.h
  inc/saiobject.h
  inc/saiprefixcompression.h
  inc/saitypes.h
Labels: reviewed

#2046 Add label attribute for Policer, RIF, Scheduler and UDF
  inc/saipolicer.h
  inc/sairouterinterface.h
  inc/saischeduler.h
  inc/saiudf.h
  meta/aspell.en.pws
Labels: reviewed

#2102 Add uSID endpoint enums for udx and udt
  inc/saisrv6.h
  meta/aspell.en.pws
Labels: reviewed

#2110 [meta] Fix iscustom attribute field
  meta/parse.pl
Labels: metadata

#2111 [meta] Make sai switch pointers attr list stable
  meta/parse.pl
  meta/saisanitycheck.c
Labels: enhancement, metadata

#2112 Add custom range base enums for api and object_type
  inc/sai.h
  inc/saitypes.h
  meta/test.pm
Labels: enhancement

#2113 [meta] Update history files
  meta/ancestry.5f75d99.history
  meta/ancestry.825c835.history
  meta/checkancestry.sh
  meta/checkstructs.sh
  meta/structs.5f75d99.history
  meta/structs.825c835.history
Labels: enhancement, metadata

#2115 [meta] Check global functions return type
  meta/parse.pl
Labels: enhancement, metadata
