Repository opencomputeproject/SAI, pull requests merged in 2024-12, with the labels that each got.

#2087 Introduce new extended port oper status notification
  doc/SAI-Proposal-Extended-Port-Notification.md
  inc/saiport.h
  inc/saiswitch.h
  meta/saisanitycheck.c
  meta/saiserializetest.c
  meta/structs.pl
Labels: feature, reviewed

#1997 Adding additional Ether pkts stats ranges for Cisco Platforms
  inc/saiport.h
  meta/checkheaders.pl
Labels: reviewed

#2089 SAI Proposal TAM stream telemetry
  doc/TAM/SAI-Proposal-TAM-stream-telemetry.md
  doc/TAM/netlink_dma_channel.drawio.svg
  inc/saiobject.h
  inc/saiswitch.h
  inc/saitam.h
  inc/saitypes.h
  meta/aspell.en.pws
Labels: reviewed

#2114 Unify SAI_HOSTIF_USER_DEFINED_TRAP_TYPE_CUSTOM_RANGE_BASE value
  inc/saihostif.h
  meta/checkheaders.pl
  meta/test.pm
Labels: breaking-change, reviewed

#2084 EVPN Multi Home Support
  doc/tunnel/SAI-Proposal-EVPN-Multihoming.md
  doc/tunnel/figures/sai_evpnmh_df.png
  doc/tunnel/figures/sai_evpnmh_failover.png
  doc/tunnel/figures/sai_evpnmh_singleactive.png
  doc/tunnel/figures/sai_evpnmh_splithorizon.png
  doc/tunnel/figures/sai_evpnmh_unicast.png
  inc/saibridge.h
  inc/sainexthop.h
  inc/sainexthopgroup.h
  inc/saivlan.h
Labels: reviewed
