Repository opencomputeproject/SAI, pull requests merged in 2024-10, with the labels that each got.

#2083 [meta] Use strinct flags on sai_port_error_status_t
  inc/saiport.h
  meta/saisanitycheck.c
Labels: enhancement, metadata

#1941 SAI Proposal for Counter enhancement.
  doc/SAI-Counter-enhancement-hld.md
  inc/saibfd.h
  inc/saibridge.h
  inc/saibuffer.h
  inc/saicounter.h
  inc/saiicmpecho.h
  inc/saiipsec.h
  inc/saimacsec.h
  inc/saipolicer.h
  inc/saiport.h
  inc/saiqueue.h
  inc/sairouterinterface.h
  inc/saisrv6.h
  inc/saiswitch.h
  inc/saitunnel.h
  inc/saitwamp.h
  inc/saitypes.h
  inc/saivlan.h
Labels: reviewed

#2066 Hostif trap type for Subnet routes
  inc/saihostif.h
Labels: reviewed

#2076 Add bulk APIs for ingress priority group and queue.
  inc/saibuffer.h
  inc/saiqueue.h
Labels: reviewed

#2071 HW Based FRR
  doc/SAI-Proposal-HW-FRR.md
  inc/sainexthopgroup.h
  inc/saiport.h
Labels: reviewed

#2003 Updating saimacsec.h to add macsec_port_id to flow obj
  inc/saimacsec.h
Labels: reviewed

#2095 [rpc] Fix missing attr value for object type enum
  meta/gensairpc.pl
Labels: bug
